import os
import json
from datetime import datetime

def generate(data, company_name):
    os.makedirs("outputs/client_briefs", exist_ok=True)
    os.makedirs("outputs/competitor_reports", exist_ok=True)

    with open(f"outputs/client_briefs/{company_name}_brief.json", "w") as f:
        json.dump(data['client_profile'], f, indent=2)

    with open(f"outputs/competitor_reports/{company_name}_competitors.json", "w") as f:
        json.dump(data['competitors'], f, indent=2)

    print("[ReportGenerator] Reports generated successfully!")

def generate_text_report(results, company_name):
    """Generate a text report file"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"outputs/{company_name}_Business_Intelligence_Report_{timestamp}.txt"
    
    os.makedirs("outputs", exist_ok=True)
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(f"BUSINESS INTELLIGENCE REPORT\n")
        f.write(f"Company: {company_name}\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"{'='*60}\n\n")
        f.write(results)
        f.write(f"\n{'='*60}\n")
        f.write("Report generated by Prelytics Business Intelligence System\n")
    
    return filename
